FRAMES := 

# sframe:	$(myfile).tex
# 	cat driver.tex | sed s/DRIVEME/$(myfile)/ > $(myfile)-sframe.tex
# 	pdflatex $(myfile)-sframe && pdflatex $(myfile)-sframe

talk:  talk.tex  $(FRAMES)
	pdflatex talk && pdflatex talk
